config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books do
    resources :reviews, except: [:destroy, :update, :edit]
    resources :swaps, only: [:new, :create]
  end
  resources :swaps, only: [:update]
  resources :user_book_relationships
  resources :users, only: [:show]
  resources :reviews, only: [:destroy]
  namespace :current_user do
    resources :swaps, only: [:index, :update]
  end
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  get "/dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_book_relationships
  has_many :books, through: :user_book_relationships
  has_many :incoming_swaps, class_name: 'Swap', foreign_key: :user_id
  has_many :requested_swaps, class_name: 'Swap', foreign_key: :swapper_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @owned_user_books = show_owned_books
    @previously_owned_user_books = show_previously_owned_user_books
  end

  private

  def show_owned_books
    @user = User.find(params[:id])
    rels = @user.user_book_relationships
    Book.where(id: rels.where(owned: true).select(:book_id))

  end

  def show_previously_owned_user_books
    @user = User.find(params[:id])
    rels = @user.user_book_relationships
    Book.where(id: rels.where(owned: false).select(:book_id))
  end

end

app/views/users/show.html.erb
<div class="p-2 font-normal">
  <%= link_to books_path do %>
    <div class="border border-slate-300 hover:border-indigo-300 p-2 w-max rounded-full justify-start space-x-2 place-items-center flex text-indigo-500/50 hover:text-indigo-600">
      <i class="fa-solid fa-circle-left"></i>
      <p class="flex-initial ">back</p>
    </div>
  <% end %>
</div>
<div class="max-w-2xl mx-4 sm:max-w-sm md:max-w-sm lg:max-w-sm xl:max-w-sm sm:mx-auto md:mx-auto lg:mx-auto xl:mx-auto mt-6 bg-white shadow-xl rounded-lg text-gray-900">
  <div class="rounded-t-lg h-32 overflow-hidden">
    <img class="object-cover object-top w-full" src='https://images.unsplash.com/photo-1549880338-65ddcdfd017b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt='Mountain'>
  </div>
  <div class="mx-auto w-32 h-32 relative -mt-16 border-4 border-white rounded-full overflow-hidden">
    <img class="object-cover object-center h-32" src= <%=@user.profile_picture %>>
  </div>
  <div class="text-center mt-2">
    <h2 class="font-semibold"><%=@user.first_name %></h2>
    <p class="text-gray-500">Book lover ❤</p>
  </div>
  <ul class="py-4 mt-2 text-gray-700 flex items-center justify-around">
    <li class="flex flex-col items-center justify-around">
      <h2 class="w-4 fill-current text-indigo-500 text-xl font-bold"> <%= @owned_user_books.count %></h2>
      </h2>
      <div>Owned books</div>
    </li>
    <li class="flex flex-col items-center justify-between">
      <h2 class="w-4 fill-current text-indigo-500 text-xl font-bold"> <%= @previously_owned_user_books.count %></h2>
      <div>Swapped books</div>
    </li>
  </ul>
  <div class="p-4 border-t mx-8 mt-2">
    <button class="w-1/2 block mx-auto rounded-full bg-indigo-500 hover:shadow-lg font-semibold text-white px-6 py-2"><%= link_to "Follow", "https://www.youtube.com/watch?reload=9&v=dQw4w9WgXcQ" %></button>
  </div>
</div>

<div class="mx-12 mb-4">
    <div class="my-4">
     <div class="mx-auto py-2 w-4/5">
      <h2 class="text-2xl mb-6 mt-2 text-indigo-400"> <%= @user.first_name %>'s books (<%= @owned_user_books.count %>)</h2>
      <div class="grid sm:grid-cols-1 gap-4 lg:grid-cols-2">
        <% @owned_user_books.each do |owned_user_book| %>
        <div class="flex flex-col md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg">
          <div class="flex justify-center">
          <%= link_to book_path(owned_user_book.id) do %>
            <%= image_tag owned_user_book.cover, class: "w-60 h-full rounded-lg" %>
          <% end %>
          </div>
          <div class="relative w-1/2 my-4 mx-4 leading-tight md:p-4">
            <h2 class="text-gray-600"><%=owned_user_book.author %></h2>
            <h1 class="text-2xl bold-700"><%=link_to owned_user_book.title.truncate(20), book_path(owned_user_book) %></h1>
            <%# <h2 class="text-xl bold"><%=book.average_rating %></h2>
            <h2 class="text-gray-600 py-4"><%=owned_user_book.description.truncate_words(25) %></h2>
            <div class="grid grid-cols-2 gap-4 place-content-between">
              <h2 class="text-gray-600 py-1 font-bold"><%=owned_user_book.language.upcase %></h2>
              <h2 class="text-gray-600 py-1 font-bold"><%=owned_user_book.condition %></h2>
            </div>
            <div class="inline-block align-bottom">
              <span class="absolute bottom-2 left-3 px-4 py-2 bg-indigo-500 text-white text-sm font-medium rounded-full">
                <%=owned_user_book.category.truncate(13) %>
              </span>
              <button
                type="button"
                class="absolute bottom-2 right-0 inline-block px-4 py-2.5 text-indigo-400 bg-white border border-indigo-400 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-indigo-400 hover:text-white hover:shadow-lg focus:bg-blue-700 focus:shadow-lg"><%=link_to "Get this book!", new_book_swap_path(owned_user_book) %>
              </button>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
 </div>


    <div class="my-4">
    <div class="mx-auto py-2 w-4/5">
    <h2 class="text-2xl my-8 text-indigo-400"> <%= @user.first_name %>'s swapped books (<%= @previously_owned_user_books.count %>)</h2>
      <div class="grid sm:grid-cols-1 gap-4 lg:grid-cols-2">
        <% @previously_owned_user_books.each do |book| %>
        <div class="flex flex-col md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg">
          <div class="flex justify-center">
          <%= link_to book_path(book.id) do %>
            <%= image_tag book.cover, class: "w-60 h-full rounded-lg" %>
          <% end %>
          </div>
          <div class="relative w-1/2 my-4 mx-4 leading-tight md:p-4">
            <h2 class="text-gray-600"><%=book.author %></h2>
            <h1 class="text-2xl bold-700"><%=link_to book.title.truncate(20), book_path(book) %></h1>
            <%# <h2 class="text-xl bold"><%=book.average_rating %></h2>
            <h2 class="text-gray-600 py-4"><%=book.description.truncate_words(25) %></h2>
            <div class="grid grid-cols-2 gap-4 place-content-between">
              <h2 class="text-gray-600 py-1 font-bold"><%=book.language.upcase %></h2>
              <h2 class="text-gray-600 py-1 font-bold"><%=book.condition %></h2>
            </div>
            <div class="inline-block align-bottom">
              <span class="absolute bottom-2 left-3 px-4 py-2 bg-indigo-500 text-white text-sm font-medium rounded-full">
                <%=book.category.truncate(13) %>
              </span>
              <button
                type="button"
                class="absolute bottom-2 right-0 inline-block px-4 py-2.5 text-indigo-400 bg-white border border-indigo-400 font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-indigo-400 hover:text-white hover:shadow-lg focus:bg-blue-700 focus:shadow-lg"><%=link_to "Get this book!", new_book_swap_path(book) %>
              </button>
              <%= link_to user_path(User.find(UserBookRelationship.find_by(owned: true, book_id: book.id).user_id)) do %>
                <% previous_user = User.find(UserBookRelationship.find_by(owned: true, book_id: book.id).user_id) %>
               <%= image_tag previous_user.profile_picture, class: "absolute top-4 right-0 w-10 rounded-full bg-neutral-500" %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
 </div>