config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books do
    resources :reviews, except: [:destroy, :update, :edit]
    resources :swaps, only: [:new, :create]
  end
  resources :swaps, only: [:update]
  resources :user_book_relationships
  resources :users, only: [:show]
  resources :reviews, only: [:destroy]
  namespace :current_user do
    resources :swaps, only: [:index, :update]
  end
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  get "/dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <footer class="mx-auto py-8 px-3 mt-12 mb-4 text-gray-800 ">
    <div class="flex -mx-3 md:text-base sm: text-xs">
      <div class="flex-1 px-3">
        <h2 class="text-lg font-semibold">Dirección</h2>
        <a href="https://goo.gl/maps/pyZuhWkCcgt3yaYa9" target="_blank">
          <p class="mt-5">San Miguel - Calacoto, Av. Montenegro esq. Ferrecio #1294, piso 1</p>
          <p class="mt-5">La Paz – Bolivia</p>
        </a>
      </div>
      <div class="flex-1 px-3">
        <h2 class="text-lg font-semibold">Teléfonos</h2>
        <ul class="mt-4 leading-loose">
          <li>
            <a href="tel:+591 76777577">+591 76777577 </a>
          </li>
          <li>
            <a href="tel:+591 (2)2115970">+591 (2)2115970</a>
          </li>
        </ul>
      </div>
      <div class="flex-1 px-3">
        <h2 class="text-lg font-semibold">E-Mail</h2>
        <ul class="mt-4 leading-loose">
          <li>
            <a href="mailto:info@vi-legal.com" target="_blank">
              info@vi-legal.com
            </a>
          </li>
        </ul>
      </div>
    </div>
  </footer> %>

<footer class="bg-white rounded-lg mt-24 shadow md:px-6 md:py-8 dark:bg-gray-800 z-10">
    <div class="sm:flex sm:items-center sm:justify-end">
            <%# <%= link_to "BOOKBOX", books_path(@book), class: "self-center text-2xl font-semibold whitespace-nowrap dark:text-white" %>
        <ul class="flex flex-wrap items-center mb-6 text-sm text-gray-500 sm:mb-0 dark:text-gray-400">
            <li>
                <%= link_to "Privacy Policy", root_path, class:"mr-4 hover:underline md:mr-6 "%>
            </li>
            <li>
                <%= link_to "Bookshelf", dashboard_path, class:"mr-4 hover:underline md:mr-6 "%>
            </li>
            <li>
                <%= link_to "Add a book", new_book_path, class:"mr-4 hover:underline md:mr-6 "%>
            </li>
            <li>
                <%= link_to "About us", root_path, class:"mr-4 hover:underline md:mr-6 "%>
            </li>
            <li>
                <%= link_to "Contact", root_path, class:"mr-4 hover:underline md:mr-6 "%>
            </li>
        </ul>
    </div>
    <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
    <span class="block text-sm text-ligth-500 bg-primary sm:text-center dark:text-gray-400">© 2022 <a href="#" class="hover:underline">Bookbox™</a>. All Rights Reserved.
    </span>
</footer>

app/views/shared/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-indigo-400 py-5">
  <div class=" px-4 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-14">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!--
            Icon when menu is open.

            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          --> <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <%# <%=link_to "BOOKBOX", root_path, class:"text-white"%>
            <%= link_to "BOOKBOX", books_path, class: "text-white px-10 py-2 text-4xl" %>
        </div>
      </div>
      <div class="hidden sm:block sm:ml-6">
        <div class="flex space-x-5">
          <% if current_user %>
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%# <a href="#" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">Bookshelf</a> %>
            <%# <%= link_to "Bookshelf", dashboard_path, class:"bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Add a book", new_book_path, class:"text-white hover:text-gray-300 px-3 py-4 text-xl"%>
            <%= link_to "My bookshelf", dashboard_path, class:"text-white hover:text-gray-300 px-3 py-4 text-xl"%>
            <%= link_to "My swaps", current_user_swaps_path, class:"text-white hover:text-gray-300 px-3 py-4 text-xl"%>
          <% end %>
        </div>
      </div>
      <div class=" inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
         <% if current_user %>
        <!-- Profile dropdown -->
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "text-white hover:text-gray-300 px-3 py-4 text-xl"%>
          <% else %>
          <%= link_to "Sign in", "/books", class: "text-white hover:text-gray-300 px-3 py-4 text-xl"%>
          <%= link_to "Sign up", "/users/sign_up", class: "text-white hover:text-gray-300 px-3 py-4 text-xl"%>
        <% end %>
        <div class="ml-3 relative">
          <div>
            <button type="button" class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" aria-label="true" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <% if current_user %>
                <img class="h-10 w-10 rounded-full" src="<%= current_user.profile_picture %>"alt="">
              <% end %>
            </button>
          </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <%# <a href="#" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium" aria-current="page">Dashboard</a> %>
      <%= link_to "Bookshelf", dashboard_path, class:"bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"%>
      <%= link_to "Add a book +", new_book_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"%>
      <%= link_to "About us", dashboard_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"%>
      <%= link_to "Contact", dashboard_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"%>

    </div>
  </div>
</nav>