config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :books do
    resources :reviews, except: [:destroy, :update, :edit]
    resources :swaps, only: [:new, :create]
  end
  resources :swaps, only: [:update]
  resources :user_book_relationships
  resources :users, only: [:show]
  resources :reviews, only: [:destroy]
  namespace :current_user do
    resources :swaps, only: [:index, :update]
  end
  resources :chatrooms, only: [:show, :new, :create] do
    resources :messages, only: :create
  end
  get "/dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_book_relationships, dependent: :destroy
 # validates :title, :cover, :location, :condition, :category, :year, :author, :description, :language, presence: true
 has_many :users, through: :user_book_relationships, dependent: :destroy

 has_many :reviews, dependent: :destroy

 has_many :swaps, dependent: :destroy

 validates :title, :cover, :condition, :author, presence: true
  geocoded_by :location
  after_validation :geocode

end

app/controllers/books_controller.rb
require "json"
require "open-uri"

class BooksController < ApplicationController
  def index
    rels = current_user.user_book_relationships
    my_books = Book.where(id: rels.where(owned: true).select(:book_id))
    hidden_books = Book.where(displayed: false)
    @books = Book.all - hidden_books - my_books
    if params[:query].present?
      @books = Book.where("title ILIKE ?", "%#{params[:query]}%") - hidden_books - my_books
    elsif  params[:category].present?
      @books = Book.where("category ILIKE ?", "%#{params[:category]}%") - hidden_books - my_books
    elsif params[:credit_worth].present?
      @books = Book.where("credit_worth ILIKE ?", "%#{params[:credit_worth]}%") - hidden_books - my_books
    else
      @books = Book.all - hidden_books - my_books
    end
    @index_distances = index_distances

    respond_to do |format|
      format.html
      format.text { render partial: 'books/results', locals: { books: @books }, formats: [:html] }
    end
  end

  def show
    @book = Book.find(params[:id])
    @swap = Swap.new
    @review = Review.new
    find_previous_owners
    find_markers
    @distance = distance(@book)
  end

  def new
    @book = Book.new
  end

  def create
    url = "https://www.googleapis.com/books/v1/volumes?q=isbn:#{book_params[:isbn]}"
    book_serialized = URI.open(url).read
    book_hash = JSON.parse(book_serialized)
    book_detail = book_hash["items"][0]["volumeInfo"]
    @book = Book.new(
      condition: book_params[:condition],
      location: current_user.address,
      title: book_detail["title"],
      author: book_detail["authors"].first,
      category: book_detail["categories"][0],
      year: book_detail["publishedDate"].to_i,
      cover: book_detail["imageLinks"]["thumbnail"],
      description: book_detail["description"],
      language: book_detail["language"],
      displayed: book_params[:displayed],
      isbn: params[:isbn]
    )

    if @book.save
      user_book_relationship = UserBookRelationship.new(
        owned: true,
        user: current_user,
        book: @book,
        address: current_user.address,
        longitude: current_user.longitude,
        latitude: current_user.latitude
      )
      user_book_relationship.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.displayed = false
    @book.save
    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to dashboard_path
  end

  private

  def find_markers
    user_book_relationship = UserBookRelationship.find_by(book: @book, owned: true)
    @markers = [
      {
        lat: user_book_relationship.latitude,
        lng: user_book_relationship.longitude
      }]
  end

  def find_previous_owners
    previous_owners_ids = UserBookRelationship.where(book: @book, owned: false).pluck(:user_id).to_a
    @previous_owners = User.find(previous_owners_ids)
  end

  def distance(book)
    unless current_user.address.nil?
      user_book_relationship = UserBookRelationship.find_by(book: book, owned: true)
      Geocoder::Calculations.distance_between([user_book_relationship.latitude, user_book_relationship.longitude], [current_user.latitude,current_user.longitude]).round
    else
    end
  end

  def index_distances
    distances = []
    unless current_user.address.nil?
      @books.each do |book|
        user_book_relationship = UserBookRelationship.find_by(book: "#{book.id}", owned: true)
        distance = Geocoder::Calculations.distance_between([user_book_relationship.latitude, user_book_relationship.longitude], [current_user.latitude,current_user.longitude]).round
        distances << distance
      end
      distances
    else
    end
  end

  def book_params
    params.require(:book).permit(:isbn, :condition, :displayed)
  end
end

app/views/books/_results.html.erb
<div data-books-target="results" class="grid gap-4 2xl:grid-cols-3 xl:grid-cols-2 mx-auto lg:grid-col-2 md:grid-cols-1 sm:max-w-sm sm:mx-auto lg:max-w-full">
        <% @books.each_with_index do |book, index| %>
        <div class="flex flex-col md:flex-row md:max-w-xl rounded-lg bg-white shadow-lg">
          <div class="flex justify-center">
          <%= link_to book_path(book.id) do %>
            <%= image_tag book.cover, class: "w-60 h-full rounded-lg" %>
          <% end %>
          </div>
          <div class="relative w-1/2 my-4 mx-4 leading-tight md:p-1">
            <h2 class="text-gray-600 text-sm py-2 h-8 overflow-hidden"><%=book.author %></h2>
            <h1 class="text-2xl bold-700 h-16 overflow-hidden"><%=link_to book.title.truncate(17), book_path(book) %></h1>
            <%# <h2 class="text-xl bold"><%=book.average_rating %></h2>
              <h2 class="text-gray-600 py-1 font-bold"><%=book.condition %></h2>
              <% if book.credit_worth == "5" %>
                <p class="text-yellow-600 mt-3 text-xl">★★★★★</p>
              <% elsif book.credit_worth == "4" %>
                <p class="text-yellow-600 mt-3 text-xl">★★★★☆</p>
              <% elsif book.credit_worth == "3" %>
                <p class="text-yellow-600 mt-3 text-xl">★★★☆☆</p>
              <% else %>
                <p class="text-yellow-600 mt-3 text-xl">★★☆☆☆</p>
              <% end %>
              <% unless current_user.address.nil? || @index_distances == [] %>
                <% if @index_distances[index] > 1 %>
                  <p class="text-gray-600 text-md"> <%= @index_distances[index] %> km</p>
                  <% else %>
                  <p class="text-gray-600 pt-1 text-md">< 1 km</p>
                  <% end %>
                <% end %>
            <div class="inline-block align-bottom">
              <button
                  class="absolute bottom-0 right-0 px-4 py-2.5 my-4 text-indigo-400 bg-white border border-indigo-400 font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-indigo-400 hover:text-white hover:shadow-lg "><%=link_to "Swap it!", new_book_swap_path(book) %>
              </button>
              <%= link_to user_path(User.find(UserBookRelationship.find_by(owned: true, book_id: book.id).user_id)) do %>
                <% previous_user = User.find(UserBookRelationship.find_by(owned: true, book_id: book.id).user_id) %>
               <%= image_tag previous_user.profile_picture, class: "absolute bottom-3.5 left-0 w-10 rounded-full bg-neutral-500" %>
              <% end %>
            </div>
          </div>
        </div>

        <% end %>

</div>

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
  <%= f.label :condition %>
  <%= f.text_field :displayed %>
  <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<div data-controller="books" class="index-container mx-auto px-4 md:px-12 bg-white">

  <div class="flex-row items-center bg-white rounded-full pt-8 pb-4 px-64 ">
    <%= form_with url: books_path, method: :get, html: { class:
        'm-2', data: { books_target: 'form' } } do |f| %>
      <%= f.text_field :query,
        class: "form-control shadow-lg appearance-none rounded-full w-full py-3  text-gray-700 border-2 text-center",
        placeholder: 'Search the Bookbox...',
        value: params[:query],
        data: {
          books_target: 'input',
          action: 'keyup->books#search'
        }
      %>
    <% end %>
  </div>

  <div class="flex mt-2 mb-4">
    <div class="info w-1/5 text-lg bg-gray-100 rounded-lg bg-white shadow-lg my-12 ">
      <%=link_to "Add a book", new_book_path, class:"w-1/2 flex justify-center m-8 px-8 py-4 shadow-lg rounded-full text-white bold bg-indigo-400 hover:bg-white hover:text-indigo-700 shadow-lg mx-auto"  %>
      <div class="m-8 pt-8 pb-4 ">
        <h1 class='text-2xl my-4'>Categories</h1>
        <div class="grid grid-cols-2">
          <ul class='text-md'>
            <li class = hover:text-indigo-400> <%= link_to "All books", books_path, data: {action: "click->books#fetchBooks"} %></li>
            <li class = hover:text-indigo-400> <%= link_to "Fiction", books_path(category: "Fiction") %></li>
            <li class = hover:text-indigo-400> <%= link_to "Cooking", books_path(category: "Cooking") %> </li>
            <li class = hover:text-indigo-400> <%= link_to "Biography", books_path(category: "Biography") %> </li>
            <li class = hover:text-indigo-400> <%= link_to "Horror", books_path(category: "B") %> </li>
            <li class = hover:text-indigo-400> <%= link_to "Comics", books_path(category: "Biography") %> </li>
            <li class = hover:text-indigo-400> <%= link_to "History", books_path(category: "Biography") %> </li>
          </ul>
        </div>
      </div>
      <div class="mx-8 my-2">
        <h1 class='text-2xl my-4'>Rating</h1>
        <ul class='text-xl text-yellow-600'>
          <li><%= link_to "★★★★★" , books_path(credit_worth: "5"), class:'' %></li>
          <li><%= link_to "★★★★☆", books_path(credit_worth: "4") %></li>
          <li><%= link_to "★★★☆☆", books_path(credit_worth: "3") %></li>
          <li><%= link_to "★★☆☆☆", books_path(credit_worth: "2") %></li>
          <li><%= link_to "★☆☆☆☆", books_path(credit_worth: "1") %></li>
        </ul>
      </div>
    </div>

    <div class="w-4/5 px-4 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-2xl md:px-12 lg:px-8 lg:py-12">
      <%= render partial: 'results', locals: { book: @books } %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="h-fit">
  <div class="px-3 h-fit text-gray-800" >

    <div class="p-2 font-normal">
      <%= link_to books_path do %>
        <div class="border border-slate-300 hover:border-indigo-300 p-2 w-max rounded-full justify-start space-x-2 place-items-center flex text-indigo-500/50 hover:text-indigo-600">
          <i class="fa-solid fa-circle-left"></i>
          <p class="flex-initial ">back</p>
        </div>
      <% end %>
    </div>

    <div class=" flex xl:justify-center lg:justify-between justify-center items-center flex-wrap h-full g-6">
      <div class=" p-8 rounded-lg h-full h-1/2 grow-0 shrink-1 md:shrink-0 basis-auto xl:w-6/12 lg:w-6/12 md:w-9/12 mb-12 md:mb-0">
        <img
          src="https://cdn.dribbble.com/users/324827/screenshots/5500303/media/d67b1dc44130fdaad6845b82e2a4a013.jpg?compress=1&resize=450x338&vertical=top"
          class="rounded-lg w-full"
          alt="Sample image"
        />
      </div>

      <div class=" p-8 rounded-lg h-full h-1/2 shadow ">
        <div class="flex-row items-center bg-white rounded p-8 ">
          <h1 class='text-2xl text-center align-center text-indigo-400'>Add a book to the Bookbox and start swapping!</h1>
        </div>
        <div class="flex-row items-center bg-white rounded p-8">
          <%= simple_form_for @book do |f| %>
            <div class="form-inputs">
              <%= f.input :isbn, input_html: {class:'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700'} %>
              <%= f.input :condition, collection: ["Used", "Good condition", "As new", "New"], input_html: {class:'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700'}%>
            </div>
            <div class="form-actions mt-6">
              <%= f.button :submit, "Add your book", class:'bg-indigo-400 hover:bg-indigo-300 shadow appearance-none border rounded w-full py-2 px-3 text-white font-bold' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="px-3">
  <div class="p-2 font-normal">
    <%= link_to books_path do %>
      <div class="border border-slate-300 hover:border-indigo-300 p-2 w-max rounded-full justify-start space-x-2 place-items-center flex text-indigo-500/50 hover:text-indigo-600">
        <i class="fa-solid fa-circle-left"></i>
        <p class="flex-initial ">back</p>
      </div>
    <% end %>
  </div>
  <div class="container my-12 mx-auto px-4 md:px-12 bg-white">
    <div class="first">
      <div class="flex mb-8 shadow-lg">
        <div class="info w-full py-4 px-32">
          <div class=''>
            <div class="flex mb-8">

              <div class='w-3/5 px-12'>
                <div class="flex justify-between">
                  <h1 class="text-4xl my-2"><%=@book.title %></h1>
                  <%= link_to user_path(User.find(UserBookRelationship.find_by(book: @book.id, owned:true).user_id)) do %>
                  <%= image_tag (User.find(UserBookRelationship.find_by(book: @book.id, owned:true).user_id)).profile_picture, class: "h-16 w-16
                  rounded-full bg-neutral-500" %>
                  <% end %>
                </div>
                <h5 class="text-gray-500 my-2"><%=@book.author %></h5>
                <p class='text-justify my-8'><%= @book.description.truncate_words(160) %></p>
                <div class='w-2/3'>
                  <div class='flex justify-between'>
                    <span class="px-4 py-2 bg-indigo-500 text-white text-lg rounded-full">
                      <h5><%= @book.category.truncate(15) %></h5>
                    </span>
                      <h5 class='text-gray-500 text-lg bold m-2'><%= @book.year %></h5>
                      <h5 class='text-gray-500 text-lg bold m-2'><%= @book.language.upcase %></h5>
                      <h5 class='text-gray-500 text-lg bold m-2'><%= @book.condition %></h5>
                  </div>
                  <% @user_book_relationship = UserBookRelationship.find_by(book: @book, user: current_user, owned: true)%>
                    <% unless @user_book_relationship %>
                      <h5 class='text-gray-500 text-lg bold mx-2 mt-6'><%= @distance %> km away</h5>
                    <% else %>
                      <%= link_to " 🗑 ",
                                          book_path(@book),
                                          method: :delete,
                                          data: { confirm: "Are you sure ?" } %>
                  <% end %>
                </div>

                <div class="w-1/2 flex justify-start mt-8">
                  <% unless @user_book_relationship %>
                    <%=link_to "Swap this book", new_book_swap_path(@book), class:"text-indigo-500 bg-white border border-indigo-500 text-xl leading-tight rounded-full shadow-md hover:bg-indigo-500 hover:text-white hover:shadow-lg mr-8 py-3 px-8 " %>
                  <% end %>
                </div>

              </div>

              <div class='w-2/5 flex justify-end align-middle my-auto'>
                <img class='w-80 object-fit rounded-lg bg-indigo-500 shadow-lg shadow-indigo-500/50' src="<%=@book.cover %>" alt="">
              </div>

            </div>
        </div>
      </div>
    </div>
      <%# changer le bg %>
    <div class=" rounded-lg">
      <div class='mx-auto my-8 pt-6 h-36 shadow-lg text-center rounded-lg shadow'>
        <h3 class='text-2xl'>Previous owners</h3>
        <div class='mt-2 flex justify-center'>
          <% if @previous_owners.empty? && @user_book_relationship %>
            <h4 class='text-lg gray'>Congrats! you are the first owner of this book.<br /> Start swapping with others to create a chain!</h4>
            <% elsif @previous_owners.empty? && @user_book_relationship == nil%>
              <h4 class='text-lg gray'>Be the first to swap this book and start the chain!</h4>
            <% else @previous_owners.each do |previous_owner| %>
              <img class="h-16 w-16 p-2 rounded-full" src="<%= previous_owner.profile_picture %>"alt="">
              <%# add other information on the user %>
              <%# add distance travelled by the book between each owner %>
            <% end %>
          <% end %>
        </div>
      </div>
      <%# changement a faire %>
        <div class='flex gap-6'>
          <div class='w-1/2 shadow-lg rounded-lg shadow'>
            <h2 class='text-2xl py-8 text-center'>Tell others about this book!</h2>
            <div class=" m-16 ">
              <div class="w-full">
                <%= simple_form_for(@review, url: book_reviews_path(@book), method: :post ) do |f| %>
                  <%= f.input :title, input_html: {class:'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700'} %>
                  <%= f.input :content, input_html: {class:'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700'}%>
                  <%= f.input :stars, input_html: {class:'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700'} %>
                  <div class="w-1/3 bg-indigo-400 my-8 mx-auto"><%= f.button :submit, class:'bg-indigo-400 hover:bg-indigo-300 shadow appearance-none border rounded w-full py-2 px-3 text-white font-bold' %></div>
                <% end %>
              </div>
            </div>

          </div>
          <div class='w-1/2 shadow-lg rounded-lg'>
            <h2 class='text-2xl text-center py-8'>Reviews</h2>
            <% @book.reviews.order("created_at DESC").take(2).each do |review|%>
            <div class='m-16 rounded-lg flex flex-col'>
              <h1 class='bg-indigo-200 text-xl py-2 px-4 rounded-t-lg'><%= review.title %></h1>
              <p class='bg-indigo-200 py-8 px-4'><%= review.content %></p>
              <div class='py-2 px-4 bg-indigo-200 rounded-b-lg text-yellow-600'>
                <% if review.stars == 5 %>
                    <p class="mt-3 text-xl">★★★★★</p>
                  <% elsif review.stars == 4 %>
                    <p class="mt-3 text-xl">★★★★☆</p>
                  <% elsif review.stars == 3 %>
                    <p class="mt-3 text-xl">★★★☆☆</p>
                  <% else %>
                    <p class="mt-3 text-xl">★★☆☆☆</p>
                  <% end %>
              </div>
            </div>
            <% end  %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="map"
      style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>